'use strict';

/**
 * PDF generation using pdfkit (pure JS — no headless browser required, so it
 * runs in any container without downloading Chromium). Both generators return
 * a Promise<Buffer> so callers can stream or upload the bytes.
 */
const PDFDocument = require('pdfkit');
const logger = require('../config/logger');

const BRAND = { primary: '#0B4DE0', dark: '#001A66', muted: '#6B7394', line: '#E2E6F0' };

/**
 * Collect a PDFDocument into a single Buffer.
 */
function toBuffer(doc) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
  });
}

function header(doc, title, subtitle) {
  doc
    .fillColor(BRAND.primary)
    .fontSize(22)
    .font('Helvetica-Bold')
    .text('TruEntry', { continued: false });
  doc
    .fillColor(BRAND.muted)
    .fontSize(9)
    .font('Helvetica')
    .text('Tertiary Education Admissions Quality Assurance');
  doc.moveDown(0.6);
  doc
    .strokeColor(BRAND.line)
    .lineWidth(1)
    .moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .stroke();
  doc.moveDown(1);
  if (title) {
    doc.fillColor(BRAND.dark).font('Helvetica-Bold').fontSize(15).text(title);
  }
  if (subtitle) {
    doc.fillColor(BRAND.muted).font('Helvetica').fontSize(9).text(subtitle);
  }
  doc.moveDown(1);
  doc.fillColor('#111111');
}

/**
 * Provisional admission letter.
 * @param {object} data { reference, applicantName, institutionName, departmentName, session, issuedDate }
 * @returns {Promise<Buffer>}
 */
async function generateAdmissionLetter(data = {}) {
  const {
    reference = 'TRU-ADM',
    applicantName = 'Applicant',
    institutionName = 'Institution',
    departmentName = 'Department',
    session = 'TruEntry',
    issuedDate = new Date().toLocaleDateString('en-GB'),
  } = data;

  const doc = new PDFDocument({ size: 'A4', margins: { top: 56, bottom: 56, left: 56, right: 56 } });
  const buffer = toBuffer(doc);

  header(doc, 'PROVISIONAL ADMISSION LETTER', `${institutionName}`);

  doc.font('Helvetica').fontSize(10).fillColor(BRAND.muted);
  doc.text(`Ref: ${reference}`, { align: 'right' });
  doc.text(`Date: ${issuedDate}`, { align: 'right' });
  doc.moveDown(1.5);

  doc.fillColor('#111111').fontSize(11);
  doc.font('Helvetica-Bold').text(`Dear ${applicantName},`);
  doc.moveDown(0.8);

  doc.font('Helvetica').fontSize(11).text(
    `We are pleased to inform you that, following a rigorous and quality-assured ` +
      `admissions review, you have been offered provisional admission into ` +
      `${institutionName} to study ${departmentName}.`,
    { align: 'justify', lineGap: 3 }
  );
  doc.moveDown(0.8);
  doc.text(
    `This offer is provisional and subject to verification of your JAMB, O-Level and ` +
      `identity records, and to final admission by the Joint Admissions and Matriculation ` +
      `Board (JAMB). You are advised to accept this offer and complete any outstanding ` +
      `registration requirements within the stipulated timeframe.`,
    { align: 'justify', lineGap: 3 }
  );
  doc.moveDown(1.2);

  // Details box
  const boxTop = doc.y;
  doc.roundedRect(doc.page.margins.left, boxTop, doc.page.width - doc.page.margins.left - doc.page.margins.right, 92, 8)
    .fillAndStroke('#F5F7FD', BRAND.line);
  doc.fillColor(BRAND.dark).font('Helvetica-Bold').fontSize(10);
  const bx = doc.page.margins.left + 16;
  let by = boxTop + 14;
  const rowsData = [
    ['Candidate', applicantName],
    ['Programme', departmentName],
    ['Institution', institutionName],
    ['Session', session],
    ['Reference', reference],
  ];
  rowsData.forEach(([k, v]) => {
    doc.fillColor(BRAND.muted).font('Helvetica').fontSize(9).text(k, bx, by, { width: 120 });
    doc.fillColor('#111111').font('Helvetica-Bold').fontSize(10).text(String(v), bx + 130, by, { width: 320 });
    by += 15;
  });
  doc.y = boxTop + 100;
  doc.moveDown(2);

  doc.font('Helvetica').fontSize(11).fillColor('#111111').text('Congratulations,', { continued: false });
  doc.moveDown(1.5);
  doc.font('Helvetica-Bold').text('Registrar');
  doc.font('Helvetica').fillColor(BRAND.muted).fontSize(9).text(institutionName);

  // Footer
  doc.fontSize(8).fillColor(BRAND.muted).text(
    'This document was generated by TruEntry. Verify its authenticity via the reference above.',
    doc.page.margins.left,
    doc.page.height - 70,
    { align: 'center', width: doc.page.width - doc.page.margins.left - doc.page.margins.right }
  );

  doc.end();
  try {
    return await buffer;
  } catch (err) {
    logger.error('Admission letter PDF generation failed', { error: err.message });
    throw err;
  }
}

/**
 * Audit-ready report with a summary band and an applicant table.
 * @param {object} data { reference, title, institutionName, summary, applicants, generatedAt }
 * @returns {Promise<Buffer>}
 */
async function generateAuditReport(data = {}) {
  const {
    reference = 'TRU-RPT',
    title = 'Admission Report',
    institutionName = 'Institution',
    summary = {},
    applicants = [],
    generatedAt = new Date().toLocaleString('en-GB'),
  } = data;

  const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margins: { top: 48, bottom: 48, left: 40, right: 40 } });
  const buffer = toBuffer(doc);

  header(doc, title, `${institutionName}  •  Generated ${generatedAt}  •  Ref ${reference}`);

  // Summary cards
  const entries = Object.entries(summary || {});
  if (entries.length) {
    const cardW = (doc.page.width - doc.page.margins.left - doc.page.margins.right - (entries.length - 1) * 8) / entries.length;
    let cx = doc.page.margins.left;
    const cy = doc.y;
    entries.forEach(([k, v]) => {
      doc.roundedRect(cx, cy, cardW, 46, 6).fillAndStroke('#F5F7FD', BRAND.line);
      doc.fillColor(BRAND.dark).font('Helvetica-Bold').fontSize(16).text(String(v), cx, cy + 8, { width: cardW, align: 'center' });
      doc.fillColor(BRAND.muted).font('Helvetica').fontSize(7).text(
        k.replace(/_/g, ' ').toUpperCase(), cx, cy + 30, { width: cardW, align: 'center' }
      );
      cx += cardW + 8;
    });
    doc.y = cy + 60;
  }

  doc.moveDown(0.5);

  // Table
  const columns = [
    { key: 'reference', label: 'Reference', w: 90 },
    { key: 'name', label: 'Candidate', w: 130 },
    { key: 'department', label: 'Department', w: 120 },
    { key: 'state', label: 'State', w: 70 },
    { key: 'jambScore', label: 'JAMB', w: 50 },
    { key: 'postUtmeScore', label: 'Post-UTME', w: 60 },
    { key: 'aggregateScore', label: 'Aggregate', w: 60 },
    { key: 'rank', label: 'Rank', w: 40 },
    { key: 'status', label: 'Status', w: 90 },
  ];
  const startX = doc.page.margins.left;

  function drawRow(row, y, isHeader) {
    let x = startX;
    doc.font(isHeader ? 'Helvetica-Bold' : 'Helvetica').fontSize(8)
      .fillColor(isHeader ? '#FFFFFF' : '#111111');
    if (isHeader) {
      doc.rect(startX, y - 2, columns.reduce((a, c) => a + c.w, 0), 16).fill(BRAND.primary);
      doc.fillColor('#FFFFFF');
    }
    columns.forEach((col) => {
      const val = row[col.key];
      doc.text(val == null || val === '' ? '—' : String(val), x + 4, y + 2, { width: col.w - 6, ellipsis: true });
      x += col.w;
    });
  }

  let y = doc.y;
  drawRow(Object.fromEntries(columns.map((c) => [c.key, c.label])), y, true);
  y += 18;

  doc.fillColor('#111111');
  applicants.forEach((a, idx) => {
    if (y > doc.page.height - 60) {
      doc.addPage();
      y = doc.page.margins.top;
      drawRow(Object.fromEntries(columns.map((c) => [c.key, c.label])), y, true);
      y += 18;
    }
    if (idx % 2 === 0) {
      doc.rect(startX, y - 1, columns.reduce((s, c) => s + c.w, 0), 15).fill('#F7F9FE');
      doc.fillColor('#111111');
    }
    drawRow(a, y, false);
    y += 15;
  });

  if (!applicants.length) {
    doc.moveDown(2).fillColor(BRAND.muted).font('Helvetica-Oblique').fontSize(10)
      .text('No applicants match this report scope.', startX, y + 10);
  }

  doc.end();
  try {
    return await buffer;
  } catch (err) {
    logger.error('Audit report PDF generation failed', { error: err.message });
    throw err;
  }
}

module.exports = { generateAdmissionLetter, generateAuditReport };
